
DROP TABLE IF EXISTS Telefone;
DROP TABLE IF EXISTS ItensVenda;
DROP TABLE IF EXISTS Estoque;
DROP TABLE IF EXISTS Dependente;
DROP TABLE IF EXISTS EnderecoFunc;
DROP TABLE IF EXISTS EnderecoCli;


DROP TABLE IF EXISTS Funcionario;
DROP TABLE IF EXISTS Cliente;
DROP TABLE IF EXISTS Venda;
DROP TABLE IF EXISTS Cargo;
DROP TABLE IF EXISTS Promocao;
DROP TABLE IF EXISTS FormaPag;
DROP TABLE IF EXISTS Produto;
DROP TABLE IF EXISTS Fornecedor;
DROP TABLE IF EXISTS Categoria;

SHOW TABLES;
